[general]
  loglevel = "notice"
  hosts = ["carbonio"]
  default_server_domain = "carbonio"
  language = "en"
  rdbms_server_type = "pgsql"

[auth.dummy]
  base_time = 5
  variance = 10

[s2s]
  default_policy = "deny"

[outgoing_pools.rdbms.default]
  scope = "global"
  strategy = "best_worker"
  workers = 10

  [outgoing_pools.rdbms.default.connection]
    driver = "pgsql"
    host = "carbonio-message-dispatcher-db"
    port = 5432
    database = "carbonio-message-dispatcher-db"
    username = "carbonio-message-dispatcher-db"
    password = "password"
    keepalive_interval = 30

[listen]
  [[listen.c2s]]
    port = 10001
    ip_address = "127.0.0.1"

  [[listen.http]]
    port = 10000
    transport.num_acceptors = 10
    transport.max_connections = 1024

    [[listen.http.handlers.mod_websockets]]
      host = "_"
      path = "/ws-xmpp"
      ping_rate = 30_000

    [[listen.http.handlers.mongoose_admin_api]]
      host = "_"
      path = "/admin"

    [[listen.http.handlers.mongoose_client_api_messages]]
      host = "_"
      path = "/api/messages/[:with]"

    [[listen.http.handlers.mongoose_client_api_contacts]]
      host = "_"
      path = "/api/contacts/[:jid]"

    [[listen.http.handlers.mongoose_client_api_rooms]]
      host = "_"
      path = "/api/rooms/[:id]"

    [[listen.http.handlers.mongoose_client_api_rooms_config]]
      host = "_"
      path = "/api/rooms/[:id]/config"

    [[listen.http.handlers.mongoose_client_api_rooms_users]]
      host = "_"
      path = "/api/rooms/:id/users/[:user]"

    [[listen.http.handlers.mongoose_client_api_rooms_messages]]
      host = "_"
      path = "/api/rooms/[:id]/messages"

    [[listen.http.handlers.mongoose_graphql_handler]]
      host = "_"
      path = "/api/graphql"
      schema_endpoint = "admin"
      username = "admin"
      password = "admin-password"

[modules.mod_muc_light]
  backend = "rdbms"
  host = "muclight.@HOST@"
  equal_occupants = true
  all_can_configure = true
  all_can_invite = true
  rooms_per_page = 10
  rooms_in_rosters = false
  max_occupants = 128

[modules.mod_disco]
  users_can_see_hidden_services = true

[modules.mod_mam]
  backend = "rdbms"
  muc.backend = "rdbms"
  muc.host = "muclight.@HOST@"
  db_message_format="mam_message_xml"
  archive_chat_markers = false
  full_text_search = true

[modules.mod_inbox]
  backend = "rdbms"
  reset_markers = ["displayed"]
  groupchat = ["muclight"]
  aff_changes = true
  remove_on_kicked = true

[modules.mod_last]
  backend = "rdbms"

[modules.mod_offline_stub]

[modules.mod_roster]
  backend = "rdbms"

[modules.mod_carboncopy]

[modules.mod_ping]
  send_pings = true
  ping_interval = 60
  timeout_action = "kill"
  ping_req_timeout = 10

[modules.mod_smart_markers]
  backend = "rdbms"

[modules.mod_presence]

[services.service_mongoose_system_metrics]
  report = false
